language: node_js
node_js:
- '5'
- '6'
deploy:
  provider: npm
  email: daniel.hoisel@prodest.es.gov.br
  api_key:
    secure: NRQnwrFH/3iOAvlYZdthiGTHtZHycsV2A3i32gTOrFXDx7k0zc4g/yhI7FzOWYBYpuebNmiIVhnpX8qcf85FkHW5jCDLKL7Znfsubl04595lsfIWt/iPASeVacEX9PBN/eIynQOY67ueCk08VmwkV5ktMKAOJ6/k/v4qsyh8Q34Uro18+PY6nUzdCUks0fXxlP/xJ65An6dHUG7rkjk72bR/5V1aRxFseRZ7PjrALlFP+psrvptktJpvZLgzhzHL5Vug8qyF9DnYsQ6yqeXB5W1Ldt9N8q7HuqhWgpEmQ3Gcj3agvMv+Sqiwhh0B3fnjiWQcliWLgIJuEP9uECflxmgbIxzMxCJ8te4iRc9648QKkpK2KqzTckiIjovmS3JW6mCHfJbzXhScWr/3Mb2hw1FaxnTN8+5v+xNcbgA+843GVoJQE8sAcy0TzbaLrPgonSESgiDtcBRG3bZhabsxXG8mj9jwEjOf3JsJW2fv6A6ChP8OO1uRe0jNn1MjX8x2WSrdrEjBVVG8g9rPdXgIY/livnJE2K3RCVvYnu3NqpJM9DMm3wwqrP/rORTTNx4o1dZXAjik1hQXON60aN/XWFlIwVBDZu6fvVvbLQ9WTFcdtMdUPmznNJ5ee4Z4lrG3TAtv1kjEcQE0vD2VLNiEftA60R3JR6HkirYkhptCG14=
  on:
    tags: true
